#!/usr/bin/env sh

if [ $(uname -s) != "Darwin" ]; then
	echo "This installer is for Mac only"
	exit 1
fi

p=`dirname "$0"`
cd "$p"

INSTPREFIX=/.
SUDO="sudo "
echo "\n\nPlease type your password to install HQStreamer2 system-wide:\n"

$SUDO mkdir -p $INSTPREFIX/Applications
$SUDO mkdir -p $INSTPREFIX/Library/Audio/Plug-Ins/VST3/
$SUDO mkdir -p $INSTPREFIX/Library/Audio/Plug-Ins/Components/

echo "Copying files..."
$SUDO cp -pR HQStreamer2.app       $INSTPREFIX/Applications/
$SUDO cp -pR HQStreamer2.vst3      $INSTPREFIX/Library/Audio/Plug-Ins/VST3/
$SUDO cp -pR HQStreamer2.component $INSTPREFIX/Library/Audio/Plug-Ins/Components/
$SUDO cp -pR HQStreamer2.appex     $INSTPREFIX/Library/Audio/Plug-Ins/Components/

echo "\n\nHQStreamer2 has been installed system-wide.\n"
echo "You may close this window now.\n\n"
