#!/usr/bin/env sh

if [ $(uname -s) != "Darwin" ]; then
	echo "This installer is for Mac only"
	exit 1
fi

p=`dirname "$0"`
cd "$p"

INSTPREFIX=${HOME}
SUDO=" "

$SUDO mkdir -p $INSTPREFIX/Applications
$SUDO mkdir -p $INSTPREFIX/Library/Audio/Plug-Ins/VST3/
$SUDO mkdir -p $INSTPREFIX/Library/Audio/Plug-Ins/Components/

echo "Copying files..."
$SUDO cp -pR HQStreamer2.app       $INSTPREFIX/Applications/
$SUDO cp -pR HQStreamer2.vst3      $INSTPREFIX/Library/Audio/Plug-Ins/VST3/
$SUDO cp -pR HQStreamer2.component $INSTPREFIX/Library/Audio/Plug-Ins/Components/
$SUDO cp -pR HQStreamer2.appex     $INSTPREFIX/Library/Audio/Plug-Ins/Components/

echo "\n\nHQStreamer2 has been installed only for this user.\n"
echo "Please note that many hosts will not support AU / AUv3 plugins"
echo "installed for only one user, and it may be difficult for you"
echo "to find the HQStreamer2 standalone app now that it has been"
echo "installed this way (it's in $INSTPREFIX/Applications, while"
echo "most of your other apps are in /Applications).\n"
echo "You may close this window now.\n\n"
